---
driver:
  name: dokken
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      image: dokken/centos-7
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
  - name: ubuntu-20.04
    driver:
      image: dokken/ubuntu-20.04
  - name: debian-9
    driver:
      image: dokken/debian-9
  - name: debian-10
    driver:
      image: dokken/debian-10
  - name: debian-11
    driver:
      image: dokken/debian-11

suites:
  - name: default
    run_list:
      - recipe[test::install_configure_agent]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      aws_cloudwatch:
        config:
          params:
            shared_credential_profile: test_profile
            shared_credential_file: /etc/test_credential_file
            http_proxy: http://192.168.0.1
            https_proxy: https://192.168.0.1
            no_proxy: http://192.168.0.10
  - name: prop
    run_list:
      - recipe[test::install_agent_with_prop]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
  - name: config
    run_list:
      - recipe[test::install_agent_with_config]
    verifier:
      inspec_tests:
        - test/integration/default
  # Does not work because init system is not set up and disabling service fails
  # - name: remove
  #   run_list:
  #     - recipe[test::install_remove_agent]
  #   verifier:
  #     inspec_tests:
  #       - test/integration/remove_agent
  - name: unit-incorrect-gpg-fingerprint
    run_list:
      - recipe[test::unit_incorrect_gpg_fingerprint]
    verifier:
      inspec_tests:
        - test/unit/default/incorrect_gpg_test.rb
