---
driver:
  name: ec2
#  aws_ssh_key_id: aws-cloudwatch-kitchen
  security_group_ids: ["sg-2fb5ea78"]
  region: us-east-1
  subnet_id:  subnet-779f9410
  iam_profile_name: ec2-cloudwatch-logs
  instance_type: t2.micro
  associate_public_ip: true
  interface: dns
  tags:
    created-by: test-kitchen

transport:
#  ssh_key: ~/.ssh/ops42-aws-cloudwatch-kitchen.pem
  connection_timeout: 10
  connection_retries: 3
  username: root
#  verbose: debug

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      image_id: ami-00e87074e52e6c9f9
    transport:
      username: centos
  - name: ubuntu-20.04
    transport:
      username: ubuntu
  - name: ubuntu-18.04
    transport:
      username: ubuntu
  - name: fedora-29
    transport:
      username: fedora

suites:
  - name: default
    run_list:
      - recipe[test::install_configure_agent]
    driver:
      tags:
        Name: test-kitchen-default
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      aws_cloudwatch:
        config:
          params:
            shared_credential_profile: test_profile
            shared_credential_file: /etc/test_credential_file
            http_proxy: http://192.168.0.1
            https_proxy: https://192.168.0.1
            no_proxy: http://192.168.0.10
