sudo: required

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

## Don't `bundle install` which takes about 1.5 mins
#install: echo "skip bundle install"

branches:
  only:
    - master

#services: docker

env:
  global:
  - KITCHEN_YAML=.kitchen.yml
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml
  matrix:
  - INSTANCE=default-centos-7
  - INSTANCE=default-debian-9
  - INSTANCE=default-debian-10
  - INSTANCE=default-debian-11
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-ubuntu-1804
  - INSTANCE=default-ubuntu-2004
  - INSTANCE=default-amazonlinux
  - INSTANCE=default-amazonlinux-2
  - INSTANCE=default-fedora-29
  - INSTANCE=prop-centos-7
  - INSTANCE=prop-debian-9
  - INSTANCE=prop-debian-10
  - INSTANCE=prop-debian-11
  - INSTANCE=prop-ubuntu-1604
  - INSTANCE=prop-ubuntu-1804
  - INSTANCE=prop-ubuntu-2004
  - INSTANCE=prop-amazonlinux
  - INSTANCE=prop-amazonlinux-2
  - INSTANCE=prop-fedora-29
  - INSTANCE=config-centos-7
  - INSTANCE=config-debian-9
  - INSTANCE=config-debian-10
  - INSTANCE=config-debian-11
  - INSTANCE=config-ubuntu-1604
  - INSTANCE=config-ubuntu-1804
  - INSTANCE=config-ubuntu-2004
  - INSTANCE=config-amazonlinux
  - INSTANCE=config-amazonlinux-2
  - INSTANCE=config-fedora-29
  - INSTANCE=remove-centos-7
  - INSTANCE=remove-debian-9
  - INSTANCE=remove-debian-10
  - INSTANCE=remove-debian-11
  - INSTANCE=remove-ubuntu-1604
  - INSTANCE=remove-ubuntu-1804
  - INSTANCE=remove-ubuntu-2004
  - INSTANCE=remove-amazonlinux
  - INSTANCE=remove-amazonlinux-2
  - INSTANCE=remove-fedora-29
  - INSTANCE=unit-incorrect-gpg-fingerprint-centos-7
  - INSTANCE=unit-incorrect-gpg-fingerprint-debian-9
  - INSTANCE=unit-incorrect-gpg-fingerprint-debian-10
  - INSTANCE=unit-incorrect-gpg-fingerprint-debian-11
  - INSTANCE=unit-incorrect-gpg-fingerprint-ubuntu-1604
  - INSTANCE=unit-incorrect-gpg-fingerprint-ubuntu-1804
  - INSTANCE=unit-incorrect-gpg-fingerprint-ubuntu-2004
  - INSTANCE=unit-incorrect-gpg-fingerprint-amazonlinux
  - INSTANCE=unit-incorrect-gpg-fingerprint-amazonlinux-2
  - INSTANCE=unit-incorrect-gpg-fingerprint-fedora-29

before_script:
#  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
#  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: kitchen verify ${INSTANCE}

#matrix:
#  include:
#    - script:
#      - chef exec delivery local all
#env: UNIT_AND_LINT=1
